services:
    laravel.test:
        container_name: DMS-Laravel
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: DMS-MySQL
        image: 'mysql:latest'
        ports:
            - '3301:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root_password'
            MYSQL_DATABASE: '${DB_DATABASE:-database}'
            MYSQL_PASSWORD: 'root_password'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 512M
        networks:
            - sail
    phpmyadmin:
        container_name: DMS-PHPMyAdmin
        image: 'phpmyadmin:latest'
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3301
            PMA_ARBITRARY: 1
        ports:
            - "8082:80"
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
